spring.application.name=ingredient-management-with-spring-boot
# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=postgres
spring.datasource.password=morgan 47
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always